// BotGenes 2023, CONFIG_VAR_BG0057

var has_subheader = true;	 // index: 32
var footerMessageUsage = false;	 // index: 53
var footerShadow = false;	 // index: 56
var footerBorder = false;	 // index: 57
var hasImageIconToggle = true;	 // index: 78
var hasTextChatIcon = false;	 // index: 79
var animate_button = false;	 // index: 90
var isHidden = true;	 // index: 91
var chat_is_open = false;	 // index: 94
var hasLogo = true;	 // index: 110
var hasSpeaker = false;	 // index: 111
var AutoSpeak = false;	 // index: 112
var canSpeak = false;	 // index: 113
var isToggle = true;	 // index: 115
var SpeakColor = "transparent";	 // index: 117
var SpeakHoverColor = "transparent";	 // index: 118
var hasMicMobile = false;	 // index: 119
var hasMicDesktop = false;	 // index: 120
var isDraggable = true;	 // index: 123
var showQuickReponse = true;	 // index: 125
var geo_enabled = true;	 // index: 127
var copyrightOutFooter = true;	 // index: 128
var hasMinimizeIcon = true;	 // index: 130
var hasMoveIcon = false;	 // index: 131
var allow_multiline = false;	 // index: 134
var noIconBtnCloseSidePanel = false;	 // index: 135
var has_side_panel = false;	 // index: 136
var side_panel_initially_open = true;	 // index: 137
var HasIconDivHidden = false;	 // index: 142
var showDivAuxMobile = false;	 // index: 144
var IconDivOnlyMobile = true;	 // index: 145
var showIconButtonOnlyInMobile = false;	 // index: 147
var isDraggableAux = false;	 // index: 160
var firstChildListButton = false;	 // index: 161
var mask = true;	 // index: 185
var openPopUp = true;	 // index: 192
var chatWidth = 371;	 // index: 24
var chatHeight = 655;	 // index: 25
var headerHeight = 70;	 // index: 29
var iterHeightContent = 0.75;	 // index: 39
var footerHeight = 64;	 // index: 50
var footerWidth = 339;	 // index: 51
var TextInputWidth = 312;	 // index: 60
var TextInputHeight = 28;	 // index: 63
var sendBtnWidth = 27;	 // index: 89
var avatarWidth = 44;	 // index: 109
var delaySpeak = 3000;	 // index: 116
var delayResponse = 500;	 // index: 124
var CalculateIterHeightFooter = 64;	 // index: 129
var heightShowDivAux = 430;	 // index: 157
var heightShowDivAuxMobile = 430;	 // index: 158
var speedEffectAux = 500;	 // index: 164
var MTsite_id = 40;	 // index: 166
var initial_promt_delay = 1000;	 // index: 249
var BotName = "Asistente Virtual";	 // index: 11
var company = "";	 // index: 12
var live = "";	 // index: 13
var YourName = "Vos";	 // index: 16
var BotErrorText = "Hubo un error en la comunicación, por favor inténtalo nuevamente.";	 // index: 17
var chat_connection_oops = "Disculpa. En un momento estoy contigo.";	 // index: 18
var inputPlaceholder = "Type your message here";	 // index: 19
var templateBG = "faceInBox";	 // index: 20
var errorBotConection = "Hola, noté un problema en la conexión. Por favor intenta más tarde.";	 // index: 21
var botNameColor = "#A31F34";	 // index: 22
var yourNameColor = "#7d7a86";	 // index: 23
var headerColor = "transparent";	 // index: 28
var hasHeader = "block";	 // index: 30
var headerTitle = "Asistente Virtual";	 // index: 31
var minHeightSubHeader = "0px";	 // index: 33
var BotBodyColor = "#E7E7E7";	 // index: 36
var BotBodyRadiusBottomRight = "0px";	 // index: 37
var BotBodyRadiusBottomLeft = "0px";	 // index: 38
var chatIconColor = "#007298";	 // index: 40
var MenuButtonColor = "#007298";	 // index: 41
var chatIconHoverColor = "#007298";	 // index: 42
var MenuButtonHoverColor = "#007298";	 // index: 43
var userbubles = "#004D66";	 // index: 44
var userbublesColor = "#ffffff";	 // index: 45
var userBoxShadow = "none";	 // index: 46
var botBoxBackground = "transparent";	 // index: 47
var botBoxTextBackground = "#FFFFFF";	 // index: 48
var botBoxShadow = "none";	 // index: 49
var footerWidthMobile = "100%";	 // index: 52
var footerMessage = "Está escribiendo un mensaje";	 // index: 54
var footerMessageSize = "0.8em";	 // index: 55
var footerBorderColor = "#000";	 // index: 58
var footerBorderWidth = "0px";	 // index: 59
var TextInputFloat = "left";	 // index: 61
var TextInputColor = "#333e48";	 // index: 64
var TextInputBorder = "none";	 // index: 65
var TextInputPaddLeft = "11px !important";	 // index: 66
var TextInputPaddRight = "11px !important";	 // index: 67
var TextInputPaddBottom = "0px !important";	 // index: 68
var TextInputPaddTop = "0px !important";	 // index: 69
var chatFontSize = "11px";	 // index: 70
var chatFontFamily = "\'Open Sans\', sans-serif";	 // index: 71
var chatFloat = "none";	 // index: 72
var LogoMaxHeight = "48px";	 // index: 73
var LogoFloat = "left";	 // index: 74
var LogoPadding = "8px";	 // index: 75
var typeBotton = "BotChatIconMaterial";	 // index: 76
var toggleBotton = "";	 // index: 77
var textChatIcon = "";	 // index: 80
var BorderRadiusTopLeft = "16px";	 // index: 81
var BorderRadiusTopRight = "16px";	 // index: 82
var BorderRadiusBottomRight = "16px";	 // index: 83
var BorderRadiusBottomLeft = "16px";	 // index: 84
var toggleIcon = "fa-comments";	 // index: 85
var sendMessageColor = "transparent";	 // index: 86
var sendMessageHoverColor = "transparent";	 // index: 87
var sendBtnMessage = "";	 // index: 88
var hasAvatar = "name";	 // index: 108
var byWho = "BotGenes";	 // index: 126
var avatarFloat = "left";	 // index: 133
var textFAQTitle = "<strong>Preguntas Frecuentes</strong>";	 // index: 138
var floatSidePanel = "right";	 // index: 140
var content_icon = "<i class=\'fa fa-question-circle\' aria-hidden=\'true\'></i>";	 // index: 143
var iconButtonClose = "<span class=\'iconCloseAux\'>X</span>";	 // index: 146
var bgTxtInputMobileAux = "72%";	 // index: 148
var whereIconDiv = "up";	 // index: 149
var floatIconDiv = "left";	 // index: 150
var whereIconDivInMobile = "up";	 // index: 151
var whereShowDivAux = "up";	 // index: 152
var positionBottomDivAux = "150px";	 // index: 153
var positionBottomDivAuxMobile = "20px";	 // index: 154
var positionTopDivAux = "70px";	 // index: 155
var positionTopDivAuxMobile = "70px";	 // index: 156
var cssFirstChildListButton = "1px solid rgb(196,205,224)";	 // index: 162
var methodEffectAux = "fadeToggle";	 // index: 163
var titleDivAux = "Preguntas frecuentes";	 // index: 165
var protocol = location.protocol;	 // index: 10
var sendBtnHeight = footerHeight;	 // index: 62
var IterHeight = 503;	 // index: 132
var right_offset_multiplier = has_side_panel ? 2:1;	 // index: 139
var widthShowDivAux = chatWidth - 15;	 // index: 159
var initialPosition = {        'right'  : 100 + right_offset_multiplier * chatWidth,        'bottom' : 30 + chatHeight    };	 // index: 141
var speaker_off_color = "black";	 // index: 183
var speaker_on_color = "black";	 // index: 184
var use_svg_icons = true;
var divide_lists_in_bubble = true;

sendBtnMessage = "<div class='sendBtnMessage'><img src='"+styled_path+"/images/send_button.svg' class='btn-image'></div>";
if (!isMobile() && $(window).height() < 700) {
	// console.log("Not mobile and small height of "+$(window).height());
	chatHeight = $(window).height() * 0.9;
	IterHeight = $(window).height() * 0.9 - 140;
	initialPosition["bottom"] = window.innerHeight*0.95;
	// console.log("Using height of "+$(window).height()*0.9);
}